### ISSUE TITLE
MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]

### ISSUE THREAD

**Issue by TommyJackson85** [giacomocerquone/angular4-mean-starter#4]
I'm having problems connecting the api [localhost: 3000] to my mongo server [localhost:27017]
Im not sure if this is a problem with my MongoDB instance setup or if its to do with the project, however Im convinced I have my instance is set up. Any help would be great.

**First I set up my Mongo Server:**

```
`Last login: Sun Nov  5 17:38:32 on ttys003
Thomass-MBP:~ thomasjackson$ mongod
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] MongoDB starting : pid=2385 port=27017 dbpath=/data/db 64-bit host=Thomass-MBP.lan
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] db version v3.4.10
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2l  25 May 2017
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] allocator: system
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] modules: none
2017-11-05T17:39:20.954+1000 I CONTROL  [initandlisten] build environment:
2017-11-05T17:39:20.955+1000 I CONTROL  [initandlisten]     distarch: x86_64
2017-11-05T17:39:20.955+1000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-11-05T17:39:20.955+1000 I CONTROL  [initandlisten] options: {}
2017-11-05T17:39:20.955+1000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2017-11-05T17:39:20.955+1000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-11-05T17:39:20.955+1000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2017-11-05T17:39:20.955+1000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
2017-11-05T17:39:21.547+1000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-11-05T17:39:21.547+1000 I NETWORK  [thread1] waiting for connections on port 27017
2017-11-05T17:39:22.015+1000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2017-11-05T17:39:27.513+1000 I NETWORK  [thread1] connection accepted from 127.0.0.1:50520 #1 (1 connection now open)
2017-11-05T17:39:27.513+1000 I NETWORK  [conn1] received client metadata from 127.0.0.1:50520 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Darwin", name: "Mac OS X", architecture: "x86_64", version: "16.7.0" } }`
```
**Then I set up my Mongo Shell/client:**

```
`Last login: Sun Nov  5 17:39:14 on ttys003
Thomass-MBP:~ thomasjackson$ mongo
MongoDB shell version v3.4.10
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.10
Server has startup warnings: 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] 
2017-11-05T17:39:21.502+1000 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
use ngMean
switched to db ngMean`
```

**Then I did my test run of the project which is showing me I'm not connected.**
```
`Last login: Sun Nov  5 17:39:57 on ttys005
Thomass-MBP:angular4-mean-starter-master thomasjackson$ npm start
> angular4-mean-starter@0.7.0 start /Users/thomasjackson/Desktop/angular4-mean-starter-master
> concurrently  "nodemon server.js" "ng serve --progress=false --no-aot --proxy-config proxy.conf.json"

[0] [nodemon] 1.12.1
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node server.js`
[0] (node:2613) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[0] ✓ App is running at http://localhost:3000 in development mode
[0]   Press CTRL-C to stop
[0] 
[0] { MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
[0]     at Pool.<anonymous> (/Users/thomasjackson/Desktop/angular4-mean-starter-master/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[0]     at emitOne (events.js:125:13)
[0]     at Pool.emit (events.js:221:7)
[0]     at Connection.<anonymous> (/Users/thomasjackson/Desktop/angular4-mean-starter-master/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[0]     at Object.onceWrapper (events.js:326:30)
[0]     at emitTwo (events.js:135:13)
[0]     at Connection.emit (events.js:224:7)
[0]     at Socket.<anonymous> (/Users/thomasjackson/Desktop/angular4-mean-starter-master/node_modules/mongodb-core/lib/connection/connection.js:187:49)
[0]     at Object.onceWrapper (events.js:324:30)
[0]     at emitOne (events.js:125:13)
[0]     at Socket.emit (events.js:221:7)
[0]     at emitErrorNT (internal/streams/destroy.js:64:8)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0]   name: 'MongoError',
[0]   message: 'failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]' }
[0] ✗ MongoDB connection error. Please make sure MongoDB is running.
[0] [nodemon] clean exit - waiting for changes before restart
[1] [Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[1] ** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
[1] [Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[1] [Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[1] [Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[1] [Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[1] [Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[1] Date: 2017-11-05T07:41:32.028Z
[1] Hash: 7586d05f5fc19f9c4c11
[1] Time: 8311ms
[1] chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
[1] chunk {main} main.bundle.js, main.bundle.js.map (main) 22.7 kB {vendor} [initial] [rendered]
[1] chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 kB {inline} [initial] [rendered]
[1] chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 56 kB {inline} [initial] [rendered]
[1] chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.78 MB [initial] [rendered]
[1] 
[1] webpack: Compiled successfully.`
```

I checked Localhost: 3000 and I couldn't see any connection. 
I also tried npm start and I got the same response.

**Then I tried NPM Run Build, and got further problems with connecting.**

```
`Last login: Sun Nov  5 17:19:12 on ttys002
Thomass-MBP:angular4-mean-starter-master thomasjackson$ npm install -g node-sass
/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass
> node-sass@4.6.0 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js
Cached binary found at /Users/thomasjackson/.npm/node-sass/4.6.0/darwin-x64-59_binding.node
> node-sass@4.6.0 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js
Binary found at /usr/local/lib/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine
+ node-sass@4.6.0
updated 1 package in 1.57s
Thomass-MBP:angular4-mean-starter-master thomasjackson$ npm run build
> angular4-mean-starter@0.7.0 build /Users/thomasjackson/Desktop/angular4-mean-starter-master
> ng build --prod
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
 10% building modules 3/4 modules 1 active ...-starter-master/public/src/styles.css[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
 10% building modules 5/6 modules 1 active ...erial/prebuilt-themes/indigo-pink.css[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
 10% building modules 6/6 modules 0 active[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring [it.](url)
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
 42% building modules 267/268 modules 1 active ...-starter-master/public/src/styles.css[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
[Browserslist] Could not parse /Users/thomasjackson/Desktop/package.json. Ignoring it.
Date: 2017-11-05T07:26:14.690Z                
Hash: 502b9816138f8ffb46f6
Time: 11970ms
chunk {0} polyfills.ead1932c1a0b3c5d5239.bundle.js (polyfills) 66.1 kB {4} [initial] [rendered]
chunk {1} main.9752c9e48ecd5c2eae4f.bundle.js (main) 23.8 kB {3} [initial] [rendered]
chunk {2} styles.522bf694d63f714200ac.bundle.css (styles) 43.2 kB {4} [initial] [rendered]
chunk {3} vendor.f8eda2bb7fbe7bb1f473.bundle.js (vendor) 679 kB [initial] [rendered]
chunk {4} inline.8f2341f832e4fd4e8f28.bundle.js (inline) 1.45 kB [entry] [rendered]
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,23): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,23): Property 'title' does not exist on type 'Object'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,23): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,23): Property 'text' does not exist on type 'Object'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,48): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,48): Property 'title' does not exist on type 'Object'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,47): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,47): Property 'text' does not exist on type 'Object'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular4-mean-starter@0.7.0 build: ng build --prod
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular4-mean-starter@0.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run cn be found in:
npm ERR!     /Users/thomasjackson/.npm/_logs/2017-11-05T07_26_14_729Z-debug.log
Thomass-MBP:angular4-mean-starter-master thomasjackson$ 
`
```

Any help would be great.

**Comment by creemerica** [comment]
You have to set your environment variables correctly. There is an env.example file you can use.

**Comment by TommyJackson85** [comment]
Thanks, I think I got it working. I typed cd into my project folder from the terminal and typed "MONGODB_URI=mongodb://localhost:27017/portfolio96 node server.js" into it. If you think I did it wrong let me know.
I also ran npm build in the project but there appears to some more errors.

**Comment by giacomocerquone** [comment]
Ok, two things:
1. You don't need a mongo shell/client for the purpose of this project
2. Part of the problem was that you were not setting up the .env file
3. The other problems you get: 

```
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,23): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,23): Property 'title' does not exist on type 'Object'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,23): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,23): Property 'text' does not exist on type 'Object'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,48): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (7,48): Property 'title' does not exist on type 'Object'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,47): Property 'todo' is private and only accessible within class 'TodoFormComponent'.
ERROR in ng:///Users/thomasjackson/Desktop/angular4-mean-starter-master/public/src/app/Todos/Components/todo-form/todo-form.component.html (11,47): Property 'text' does not exist on type 'Object'.
```

These are errors you get when you build the project with aot. I'll fix them in the next commit (you can also fix them yourself), but if you launch the project with `npm start` you shouldn't have any problems to run the project smoothly

**Comment by TommyJackson85** [comment]
Thanks giacomocerquone! I appreciate your help.

**Comment by giacomocerquone** [comment]
A pleasure, thank you for using my starter 😃

**Comment by TommyJackson85** [comment]
I'm sorry giacomocerquone, do you know some tutorial that shows you how to set up the .env file? Particularly in relation to what you have set up already? Still haven't figured it out.

**Comment by giacomocerquone** [comment]
Try this:

```
PORT=3000
MONGODB_URI=mongodb://localhost:27017/ngMean
MONGOLAB_URI=
```

**Comment by TommyJackson85** [comment]
Yeah I noticed this from the env.example file. I just realised it wasn't connected properly. From 'dotenv.load' in the server.js file, the path was linking to '.env' and not '.env.example'. Maybe you left it like this for security reasons. 

Regardless, I renamed the .env.example file to another name. I linked that name in dotenv.load. It seems to be working now when I run 'npm run start' or 'npm start'. If I did this wrong, let me know. 

EDIT: just one more thing. npm run build is still bringing up the errors. Not sure if you fixed them because I'm still using the same file I downloaded the last two weeks. 

Anyway, thanks for your help. :)

**Comment by giacomocerquone** [comment]
Let's go in order.
If the problem was related to the wrong filename, you should have notice that from the error in the console. Then the reason why I put a different name in dotenv.load is because a true env file (and not the example as you saw in the repo) **must** not be committed into source control because it contains sensitive information like API keys etc.
I suggest you to read stuff like this: https://laracasts.com/discuss/channels/general-discussion/best-practices-for-storing-your-env-files https://wiki.saucelabs.com/display/DOCS/Best+Practice%3A+Use+Environment+Variables+for+Authentication+Credentials

For the build, I should have fix them, I'll check out asap.

Bye :)

**Comment by giacomocerquone** [comment]
Build problems solved in last commit :) enjoy

**Comment by barnabasgre** [comment]
all I did was to delete node modules folder In my project and do npm install to re-install it and the error disappeared. hope it works for you too

**Comment by giacomocerquone** [comment]
hey there, this repo is definitely outdated! Let me put the repo in archive mode
